# Default values for go-web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: abhi0874/chat-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "17276044888"

service:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 5000
      nodePort: 30080
      protocol: TCP
  annotations: {}
  labels: {}