apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  IngressClassName: nginx
  rules:
  - host: "chatapp.example.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: chat-app
            port: 
              number: 80