apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  labels:
    app: chat-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

      env:
          - name: MONGO_DB_URI
            valueFrom:
              secretKeyRef:
                name: chat-app-db-secret
                key: MONGO_DB_URI

          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: chat-app-db-secret
                key: JWT_SECRET