apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  labels:
    app: chat-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app-container
        image: abhi0874/chatapp-multistage:{{ .Values.image.tag}}
        ports:
        - containerPort: 8000

        env:
          - name: MONGO_DB_URI
            valueFrom:
              secretKeyRef:
                name: chat-app-db-secret
                key: MONGO_DB_URI

          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: chat-app-db-secret
                key: JWT_SECRET