apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app
spec:
  rules:
    - host: chatapp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-app
                port:
                  number: 8000
