apiVersion: v1
kind: Service
metadata:
  name: external-backend
  namespace: default
spec:
  type: ExternalName
  externalName: chat-app-yt.onrender.com
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP