name: chat-app
on: push

env:
    DATABASE_URI: ${{secrets.DATABASE_URI}}
    JWT_SECRET: ${{secrets.JWT_SECRET}}

jobs:
    Unit-Testing:

        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'

        - name: Install dependecies
          run: npm ci

        - name: Build the app
          run:  npm run build

        - name: Run unit tests 
          run: npm test

    Run-A-Container:
        runs-on: ubuntu-latest
        needs: Unit-Testing

        steps:
        - name: Install Docker
          run: sudo apt-get install docker.io -y

        - name: Run Docker container
          run: docker run -d -p 8000:8000 abhi0874/chatapp-multistage:v1
        
        - name: Display running containers
          run: docker ps | grep abhi0874/chatapp-multistage
